# This is a basic workflow to help you get started with Actions

name: push-build-check

# Controls when the workflow will run
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3.2.1
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.18 # optional
      - name: build
        run: |
          go mod tidy
          cd example
          Get-ChildItem *.go | foreach {
            $exeName = ($_.Name -replace '\.go$').exe
            go build -o ..\bin\$exeName $($_.Name) 
          }
          dir ..\bin\

      - name: download test input file
        run: |
          Invoke-WebRequest -URI 'https://github.com/orestonce/gomedia/releases/download/example/input.7z' -OutFile 'input.7z'
          7z x input.7z
          mkdir output
          
      - name: test convert_ts_to_mp4
        run: |
          Set-PSDebug -Trace 1
          .\bin\convert_ts_to_mp4.exe .\input\issue-30.ts .\output\issue-30.mp4
          .\bin\convert_ts_to_mp4.exe .\input\simple-ts.ts .\output\simple-ts.mp4
          dir output